/**
 * BİST hisse kodu → şirket adı eşlemesi
 * Lokal arama için kullanılır (Yahoo Finance'e bağımlılığı kaldırır)
 */

export const STOCK_NAMES: Record<string, string> = {
  // BİST 30
  AKBNK: "Akbank",
  ARCLK: "Arçelik",
  ASELS: "Aselsan",
  BIMAS: "BİM Mağazalar",
  EKGYO: "Emlak Konut GYO",
  ENERY: "Enerjisa Enerji",
  EREGL: "Ereğli Demir Çelik",
  FROTO: "Ford Otosan",
  GARAN: "Garanti BBVA",
  GUBRF: "Gübre Fabrikaları",
  HEKTS: "Hektaş",
  ISCTR: "İş Bankası C",
  KCHOL: "Koç Holding",
  KOZAA: "Koza Altın",
  KOZAL: "Koza Madencilik",
  KRDMD: "Kardemir D",
  MGROS: "Migros",
  ODAS: "Odaş Elektrik",
  OYAKC: "Oyak Çimento",
  PETKM: "Petkim",
  PGSUS: "Pegasus",
  SAHOL: "Sabancı Holding",
  SASA: "SASA Polyester",
  SISE: "Şişecam",
  TAVHL: "TAV Havalimanları",
  TCELL: "Turkcell",
  THYAO: "Türk Hava Yolları",
  TOASO: "Tofaş Oto",
  TUPRS: "Tüpraş",
  YKBNK: "Yapı Kredi",

  // BİST 50 ek
  AEFES: "Anadolu Efes",
  AKSA: "Aksa Akrilik",
  ALARK: "Alarko Holding",
  CIMSA: "Çimsa",
  DOHOL: "Doğan Holding",
  EGEEN: "Ege Endüstri",
  ENKAI: "Enka İnşaat",
  GESAN: "Giresun San.",
  ISGYO: "İş GYO",
  KONTR: "Kontrolmatik",
  LOGO: "Logo Yazılım",
  MPARK: "MLP Sağlık",
  OTKAR: "Otokar",
  QUAGR: "QUA Granite",
  SKBNK: "Şekerbank",
  SMRTG: "Smartiks",
  SOKM: "Şok Marketler",
  TTKOM: "Türk Telekom",
  ULKER: "Ülker",
  VESTL: "Vestel",

  // BİST 100 ek
  ADEL: "Adel Kalemcilik",
  AGESA: "Agesa Hayat",
  AGHOL: "AG Anadolu Grubu",
  AKFGY: "Akfen GYO",
  AKSEN: "Aksa Enerji",
  ALFAS: "Alfa Solar",
  ALKIM: "Alkim Kimya",
  ANSGR: "Anadolu Sigorta",
  AYGAZ: "Aygaz",
  BASGZ: "Başkent Doğalgaz",
  BIOEN: "Biotrend Enerji",
  BRISA: "Brisa",
  BRYAT: "Borusan Yatırım",
  BUCIM: "Bursa Çimento",
  CCOLA: "Coca-Cola İçecek",
  DOAS: "Doğuş Otomotiv",
  ECILC: "Eczacıbaşı İlaç",
  ENJSA: "Enerjisa",
  EUPWR: "Europower Enerji",
  GENIL: "Gen İlaç",
  GLYHO: "Global Yatırım Holding",
  HALKB: "Halkbank",
  INDES: "İndeks Bilgisayar",
  IPEKE: "İpek Enerji",
  ISMEN: "İş Yatırım Menkul",
  KAREL: "Karel Elektronik",
  KARSN: "Karsan Otomotiv",
  KLRHO: "Kiler Holding",
  KMPUR: "Kaleseramik",
  KORDS: "Kordsa",
  KTLEV: "Kontrolmatik",
  MAVI: "Mavi Giyim",
  NETAS: "Netaş Telekom.",
  PAPIL: "Papilon Savunma",
  PEKGY: "Peker GYO",
  POLHO: "Polisan Holding",
  PRKME: "Park Elektrik",
  RGYAS: "Reysaş GYO",
  SANEL: "Sanel Enerji",
  SELEC: "Selçuk Ecza",
  TGSAS: "TGS Dış Ticaret",
  TKFEN: "Tekfen Holding",
  TMSN: "Tümosan",
  TRGYO: "Torunlar GYO",
  TURSG: "Türkiye Sigorta",
  VAKBN: "Vakıfbank",
  YEOTK: "Yeo Teknoloji",
  AYEN: "Ayen Enerji",
  TATGD: "Tat Gıda",
  CLEBI: "Çelebi Havacılık",

  // Diğer önemli hisseler
  ACSEL: "Acıselsan Acıpayam Selüloz",
  AHGAZ: "Ahlatcı Doğalgaz",
  AKCNS: "Akçansa",
  AKFYE: "Akfen Yenilenebilir",
  AKMGY: "Akmerkez GYO",
  AKSGY: "Akiş GYO",
  ALCAR: "Alarko Carrier",
  ALCTL: "Alcatel Lucent",
  ALGYO: "Alarko GYO",
  ALTNY: "Altınyağ",
  ANHYT: "Anadolu Hayat",
  ARSAN: "Arsan Tekstil",
  ARZUM: "Arzum",
  ASTOR: "Astor Enerji",
  ASUZU: "Anadolu Isuzu",
  ATAGY: "ATA GYO",
  ATAKP: "Atakey Patates",
  ATATP: "Ata Teknoloji",
  AVHOL: "Avrasya Holding",
  AYCES: "Altınyunus Çeşme",
  AYDEM: "Aydem Enerji",
  BAKAN: "Bakan Elektronik",
  BANVT: "Banvit",
  BERA: "Bera Holding",
  BFREN: "Bosch Fren",
  BINHO: "Binaların Holding",
  BMELK: "BMS Birleşik Metal",
  BMSTL: "BMS Çelik",
  BNTAS: "Bantaş Ambalaj",
  BRLSM: "Birleşim Mühendislik",
  BTCIM: "Batıçim",
  BURCE: "Burçelik",
  CASA: "Casa Emtia",
  CEMAS: "Çemaş Döküm",
  CMENT: "Çimentaş",
  CUSAN: "Çuhadaroğlu",
  CVKMD: "CVK Maden",
  DAPGM: "DAP Gayrimenkul",
  DESA: "Desa Deri",
  DGATE: "Datagate",
  DGNMO: "Doğanlar Mobilya",
  DIRIT: "Dirit Enerji",
  DITAS: "Ditaş",
  DJIST: "DJIST ETF",
  DMRGD: "DMR Unlu Gıda",
  DNISI: "Dinamik ISI",
  DURDO: "Duran Doğan",
  DYOBY: "DYO Boya",
  EDATA: "E-Data Teknoloji",
  EDIP: "Edip Gayrimenkul",
  EMKEL: "Emkel Elektrik",
  ENSRI: "Ensar Enerji",
  EPLAS: "Egeplast",
  ERBOS: "Erbosan",
  ESEN: "Esenboğa Elektrik",
  ETILR: "Etiler Gıda",
  EUREN: "Euro Enerji",
  FADE: "Fade Gıda",
  FLAP: "Flap Kongre",
  FMIZP: "F-M İzmit Piston",
  FONET: "Fonet Bilgi",
  FORMT: "Formet Çelik",
  FRIGO: "Frigo-Pak Gıda",
  GEDIK: "Gedik Yatırım",
  GENTS: "Gentaş",
  GLBMD: "Global Menkul Değerler",
  GLCVY: "Galata Wind",
  GOKNR: "Gökberk Enerji",
  GOLTS: "Goldaş",
  GOODY: "Goodyear",
  GSDHO: "GSD Holding",
  GSRAY: "Galatasaray Sportif",
  GWIND: "Galata Wind",
  HATEK: "Hateks",
  HDFGS: "Hedef Girişim",
  HEDEF: "Hedef Holding",
  HKTM: "Hidropar",
  HTTBT: "Hitit Bilgisayar",
  HUBVC: "Hub Girişim",
  HUNER: "Hüner Şekercilik",
  IDEAS: "IDeaS",
  IHEVA: "İheva",
  IHLGM: "İhlâs Gayrimenkul",
  IHYAY: "İhlas Yayın",
  IMASM: "İmas Makina",
  INTEM: "İntem",
  INVEO: "Inveo Yatırım",
  ISATR: "İş B Tipi",
  ISDMR: "İskenderun Demir",
  ISFIN: "İş Finansal",
  IZENR: "İzdemir Enerji",
  JANTS: "Jantsa Jant",
  KAYSE: "Kayseri Şeker",
  KCAER: "Kalyon Enerji",
  KFEIN: "Kafein Yazılım",
  KGYO: "Koray GYO",
  KLKIM: "Kalekim",
  KLMSN: "Klimasan",
  KLSER: "Kaleseramik",
  KNFRT: "Konfrut Gıda",
  KONYA: "Konya Çimento",
  KOPOL: "Koza Polyester",
  KRONT: "Kron Telekomünikasyon",
  KRPLS: "Koroplast",
  KRVGD: "Kervan Gıda",
  KUTPO: "Kütahya Porselen",
  KUYAS: "Kuyas Çelik",
  LIDER: "Lider Faktoring",
  LILAK: "Lilak Pil",
  LKMNH: "Lokman Hekim",
  LUKSK: "Luks Kadife",
  MAALT: "Maarif Altın",
  MACKO: "Maçkolik",
  MAGEN: "M.A. Enerji",
  MAKIM: "Makina Takım",
  MANAS: "Manas Enerji",
  MEGAP: "Mega Polietilen",
  MEPET: "Mepet Metro",
  MERCN: "Mercan Kimya",
  MERKO: "Merko Gıda",
  MIATK: "Mia Teknoloji",
  MMCAS: "MMC San.",
  MOBTL: "Mobtl",
  MRGYO: "Marti GYO",
  MTRKS: "Matriks Bilgi",
  MTRYO: "Metro Yatırım",
  NUGYO: "Nurol GYO",
  NUHCM: "Nuh Çimento",
  OBASE: "Obase Bilgi",
  OFSYM: "Ofis Yem",
  ONCSM: "Oncosem",
  ORCAY: "Orcay Ortaköy",
  ORGE: "Orge Enerji",
  OSMEN: "Osmaniye Elektrik",
  OSTIM: "Ostim Endüstriyel",
  OYYAT: "Oyak Yatırım",
  OZGYO: "Özderici GYO",
  OZKGY: "Özerden GYO",
  PAMEL: "Pamel Yenilenebilir",
  PCILT: "PC İletişim",
  PENGD: "Penguen Gıda",
  PENTA: "Penta Teknoloji",
  PETUN: "Pınar Et Un",
  PINSU: "Pınar Su",
  PKART: "Plastikkart",
  PLTUR: "Pelit Turizm",
  PNLSN: "Panelsan",
  POLTK: "Polifarma",
  PRZMA: "Prizma Pres",
  PSDTC: "Pozitif Dış Tic.",
  RALYH: "Rally Enerji",
  RODRG: "Rodrigo Tekstil",
  RTALB: "RTA Laboratuvar",
  RUBNS: "Rubenis",
  RYGYO: "Reysaş GYO",
  RYSAS: "Reysaş Taşımacılık",
  SAMAT: "Sanat Madencilik",
  SDTTR: "SDT",
  SEKFK: "Seker Finansal",
  SEKUR: "Sekuro Plastik",
  SILVR: "Silverline Endüstri",
  SKYLP: "Skyalp Finansal",
  SMART: "Smart Güneş",
  SNGYO: "Sinpaş GYO",
  SNPAM: "Sınai Park",
  SODSN: "Sodaş",
  SRVGY: "Servet GYO",
  TABGD: "Taze Balık Gıda",
  TBORG: "Tuborg",
  TDGYO: "Trend GYO",
  TEKTU: "Tek-Art Turizm",
  TEMPO: "Tempo Otomat",
  TETMT: "Tetamat Gıda",
  TLMAN: "Tilmen Tarım",
  TMPOL: "Temapol Polimer",
  TNZTP: "Taze Kuru Gıda",
  TRCAS: "Turcas Petrol",
  TRILC: "Turk İlaç",
  TSGYO: "TSKB GYO",
  TTRAK: "Türk Traktör",
  TUKAS: "Tukaş",
  TUREX: "Tureks Turizm",
  UFUK: "Ufuk Finansal",
  ULAS: "Ulaşlar Turizm",
  ULUUN: "Ulusoy Un",
  USAK: "Uşak Seramik",
  VBTYZ: "VBT Yazılım",
  VERTU: "Verusaturk GYO",
  VERUS: "Verusa Holding",
  VKGYO: "Vakıf GYO",
  YATAS: "Yataş",
  YGYO: "Yeşil GYO",
  YKSLN: "Yükselen Çelik",
  YUNSA: "Yünsa",
  ZEDUR: "Zedur Enerji",
  ZOREN: "Zorlu Enerji",

  // Alt Pazar
  ADANA: "Adana Çimento A",
  ADNAC: "Adana Çimento C",
  AFYON: "Afyon Çimento",
  AKENR: "Ak Enerji",
  ALKA: "Alka Tekstil",
  ARENA: "Arena Bilgisayar",
  ARMDA: "Armada Bilgisayar",
  AVOD: "A.V.O.D Gıda",
  BAGFS: "Bandırma Gübre",
  BAKAB: "Bak Ambalaj",
  BALAT: "Balatacilar",
  BARMA: "Barış Menkul",
  BESUN: "Beşiktaş Futbol",
  BEYAZ: "Beyaz Filo",
  BLCYT: "Bilici Yatırım",
  BMSCH: "Bosch Sanayi",
  BOSSA: "Bossa",
  BRMEN: "Birlik Mensucat",
  BRSAN: "Borusan Mannesmann",
  CANTE: "Çan2 Termik",
  CELHA: "Çelik Halat",
  CMBTN: "Çimbeton",
  DAGHL: "Dağ Holding",
  DERIM: "Derimod",
  DESPC: "Despec Bilgisayar",
  DGKLB: "Doğan Burda",
  DMSAS: "Demisaş Döküm",
  DOBUR: "Doğanlar Boru",
  DOKTA: "Döktaş",
  EGPRO: "Egepro",
  EMNIS: "Eminiş Ambalaj",
  EYGYO: "EY GYO",
  GARFA: "Garanti Faktoring",
  GRNYO: "Garanti Yatırım",
  GSDDE: "GSD Denizcilik",
  GUSGR: "Güneş Sigorta",
  HURGZ: "Hürriyet Gazetecilik",
  IZFAS: "İzmir Fuar",
  IZOCM: "İzocam",
  KAPLM: "Kaplamin",
  KARYE: "Kartal Yenilenebilir",
  KENT: "Kent Gıda",
  KERVT: "Kerevitaş",
  KIMMR: "Kimteks",
  KLNMA: "T. Kalkınma Bankası",
  KRTEK: "Kartonsan",
  LINK: "Link Bilgisayar",
  MAKTK: "Maktek",
  MNDRS: "Menderes Tekstil",
  MRSHL: "Marshall",
  NTGAZ: "Naturelgaz",
  NTHOL: "Net Holding",
  OLMIP: "Olimpiyat Holding",
  OYAYO: "Oyak Yatırım Ortaklığı",
  OZBAL: "Özbal Çelik",
  PARSN: "Parsan",
  PNSUT: "Pınar Süt",
  RAYSG: "Ray Sigorta",
  ROYAL: "Royal Halı",
  SAYAS: "Say Reklamcılık",
  SEGYO: "Seker GYO",
  SELGD: "Selçuk Gıda",
  SERVE: "Serve Data",
  SKTAS: "Söktaş Tekstil",
  SNKRN: "Senkron Güvenlik",
  SUMAS: "Sumaş",
  SURGY: "Sur GYO",
  TKURU: "Taze Kuru Gıda",
  TSPOR: "Trabzonspor Sportif",
  TUCLK: "Tuğçelik",
  ULUSE: "Ulusoy Elektrik",
  VANGD: "Vanet Gıda",
  YAPRK: "Yaprak Süt",
  YGGYO: "Yeni Gimat GYO",
  ZRGYO: "Ziraat GYO",

  // GİP
  ALVES: "Alves Kablo",
  ARTMS: "Artemis Halı",
  ATSYH: "Atlantis Yatırım",
  BJKAS: "Beşiktaş Futbol",
  DARDL: "Dardanel",
  EKIZ: "Ekiz Kimya",
  ERSU: "Ersu Gıda",
  ETYAT: "Euro Trend Yatırım",
  FENER: "Fenerbahçe Futbol",
  GIPTA: "Gıpta Kırtasiye",
  GZNMI: "Gezinomi",
  HALIT: "Halitçelik",
  INGRM: "Ingram Micro",
  ISKPL: "İskenderun Polipropilen",
  KATMR: "Katmerciler",
  KUVVA: "Kuvva Maden",
  MEGMT: "Mega Metal",
};
